In [38]:
import torch

In [39]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
x.shape

torch.Size([12])

In [41]:
x.numel()

12

In [42]:
X = x.reshape(3, 4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [43]:
X = x.reshape(4, -1)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [44]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [45]:
torch.randn(3, 4)

tensor([[ 1.5888,  0.6826, -0.6094,  0.0768],
        [ 1.1961,  0.2233, -0.1738,  1.6310],
        [ 0.6460, -0.2699, -1.0071, -1.1362]])

In [46]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [47]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [48]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [49]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# X, Y
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [50]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [51]:
X.sum()

tensor(66.)

In [52]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [53]:
# Broadcasting
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [54]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [55]:
X[1, 2] = 999
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 999.,   7.],
        [  8.,   9.,  10.,  11.]])

In [56]:
X[0:2, :] = 12
X, Y

(tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [59]:
before = id(Y)
Y = Y + X
id(Y) == before
Y, before, id(Y)

(tensor([[38., 37., 40., 39.],
         [37., 38., 39., 40.],
         [28., 30., 32., 34.]]),
 1887172998592,
 1887173205264)

In [64]:
Z = torch.zeros_like(Y)
before = id(Z)
print(f"id(Z): {before}")
print(Z)
Z[:] = X + Y
after = id(Z)
print(f"id(Z): {after}")
Z, before==after

id(Z): 1887173201744
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 1887173201744


(tensor([[50., 49., 52., 51.],
         [49., 50., 51., 52.],
         [36., 39., 42., 45.]]),
 True)

In [67]:
A = X.numpy()
B = torch.tensor(A)
A, B, type(A), type(B)


(array([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]),
 numpy.ndarray,
 torch.Tensor)

In [68]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)