In [3]:
import os
import sys
current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.insert(0, parent_dir)


import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

true_w, true_b, features, labels

(tensor([ 2.0000, -3.4000]),
 4.2,
 tensor([[ 1.4255, -1.0842],
         [-0.5872,  0.6903],
         [ 1.3279,  0.1280],
         ...,
         [-1.0453, -0.2940],
         [-0.1275, -0.4182],
         [-0.2864, -0.1586]]),
 tensor([[ 1.0728e+01],
         [ 6.4678e-01],
         [ 6.4217e+00],
         [ 7.8497e+00],
         [ 3.7741e+00],
         [ 1.0872e+01],
         [-1.0582e+00],
         [ 8.4025e+00],
         [-1.8325e+00],
         [ 5.7854e+00],
         [ 1.3029e+01],
         [ 5.7728e+00],
         [ 3.0912e+00],
         [ 1.0608e+00],
         [ 1.0801e+01],
         [ 5.4750e+00],
         [-8.3196e-01],
         [ 3.4565e+00],
         [ 7.4044e+00],
         [ 5.6816e+00],
         [ 6.1174e+00],
         [ 2.3532e+00],
         [ 3.4193e+00],
         [ 1.3847e+01],
         [ 1.0989e+00],
         [-1.9457e+00],
         [ 7.9310e+00],
         [ 7.4112e+00],
         [ 4.1233e+00],
         [ 6.1390e+00],
         [ 3.1682e+00],
         [ 3.5935e+00],
       